# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb541b7d1a0dcd8701ad800daae9532e7970d4d1308fdc5765fffd778f9e0138a03870d486a6e360907c6d2df0a783c4a56969167beddbb192fc46fdb66e6315

test:
  secret_key_base: cba1d6c9dd42a7755365418ab1f92eb1c0a32092554062aa438334c2f48d47b3e84b4c59ae0a85de6e24ba4f8346fcbbcf79e8e6f15157cef12138a8e91543c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
